name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set Node.js for Build And Deploy
        uses: actions/setup-node@v3
        with:
          node-version: '18.13'
      - name: Run custom script
        run: |
          echo "npm install and build"
          npm install -g @angular/cli@16.2.10
          npm install
      - name: List files in directory
        run: |
          ls -R src/
          ls -R src/environments/
      - name: Replace environment variables
        run: |
          sed -i "s#REPLACE_WITH_GITHUB_SECRET_API_URL#${{ secrets.API_URL }}#g" src/environments/environment.ts
          sed -i "s#REPLACE_WITH_GITHUB_SECRET_API_KEY#${{ secrets.API_KEY }}#g" src/environments/environment.ts
          sed -i "s#REPLACE_WITH_GITHUB_SECRET_API_URL#${{ secrets.API_URL }}#g" src/environments/environment.prod.ts
          sed -i "s#REPLACE_WITH_GITHUB_SECRET_API_KEY#${{ secrets.API_KEY }}#g" src/environments/environment.prod.ts
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GROUND_0C1A6D00F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/secrets-in-angular-app/browser" # Built app content directory - optional
          skip_app_build: false # Skip build step of app if it is not required - optional
          skip_api_build: true # Skip build step of api if it is not required - optional
        env:  # Put a node version on the following line
          NODE_VERSION: 18.14.0
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GROUND_0C1A6D00F }}
          action: "close"
